add experimental package to compare different ways of calculating …
Ferlab-Ste-Justine/ui-etl pull request #11
Opened 2021-08-31 19:41 UTC by schammass

…the similarities between two names from two dataframes

2021-08-31 21:03 UTC, botekchristophe requested changes

2021-08-31 21:03 UTC, botekchristophe commented on build.sbt
> +libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.1.2"
you don't need to import this a second time, it's already line 17. I can show you tomorrow how to execute classes that are using  'Provided' dependencies in IntelliJ.

2021-08-31 21:03 UTC, botekchristophe commented on src/main/scala/bio/ferlab/ui/etl/experimental/Experimental.scala
> +  def levensteinScore(x: DataFrame, y: DataFrame): DataFrame = {
it would be good to add some logic to make the levenstein value a score between 0 and 1.

2021-08-31 21:03 UTC, botekchristophe commented on src/main/scala/bio/ferlab/ui/etl/experimental/Experimental.scala
> +  def cosineDistance(x: DataFrame, y: DataFrame): DataFrame = {
in fact for all scores it would be good to make them always between 0 and 1 where 0 would means 'don't match' and 1 is a match at 100%

2021-09-01 12:57 UTC, schammass commented on build.sbt
> +libraryDependencies += "com.github.mrpowers" %% "spark-stringmetric" % "0.4.0"
merci. c'est fait.

2021-09-01 12:58 UTC, schammass commented on build.sbt
> +libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.1.2"
merci.

2021-09-01 12:58 UTC, schammass commented on src/main/scala/bio/ferlab/ui/etl/experimental/Experimental.scala
> +  def levensteinScore(x: DataFrame, y: DataFrame): DataFrame = {
ok. I'm gonna work on that.

2021-09-01 12:58 UTC, schammass commented on src/main/scala/bio/ferlab/ui/etl/experimental/Experimental.scala
> +  def levensteinScore(x: DataFrame, y: DataFrame): DataFrame = {
thanks

2021-09-10 14:50 UTC, botekchristophe requested changes

2021-09-10 14:50 UTC, botekchristophe commented on src/main/scala/experimental/FuzzyMatching.scala
> +  //val df1 = spark.read.option("header", "true").csv(path1).withColumn("full_name1",
you should remove all unused comments

2021-09-10 14:50 UTC, botekchristophe commented on src/main/scala/experimental/FuzzyMatching.scala
> +      .where(col("levenshtein_score_pct") >= threshold) // .filter(col("levenshtein_score_pct") >= threshold) // same thing
I would remove this comment too

2021-09-10 14:50 UTC, botekchristophe commented on src/test/scala/bio/ferlab/ui/etl/experimental2/Testing.scala
> +package bio.ferlab.ui.etl.experimental2
no need of a second package 'experimental2' all classes should be in 'experimental'

2021-09-10 14:50 UTC, botekchristophe commented on src/test/scala/bio/ferlab/ui/etl/experimental2/Testing.scala
> +object Testing extends App {
The class name and file name should be the same as the class you are testing with 'Spec' added at the end

Here it should be FuzzyMatchingSpec

2021-09-10 14:50 UTC, botekchristophe commented on src/test/scala/bio/ferlab/ui/etl/experimental_test/FuzzyMatchingSpec.scala
> +package bio.ferlab.ui.etl.experimental_test
package bio.ferlab.ui.etl.experimental_test
should become
package bio.ferlab.ui.etl.experimental

2021-09-10 14:50 UTC, botekchristophe commented on src/test/scala/bio/ferlab/ui/etl/experimental_test/FuzzyMatchingSpec.scala
> +class FuzzyMatchingSpec extends AnyFlatSpec with WithSparkSession with Matchers {
The rest of the class is good :) 👍

2021-09-14 14:31 UTC, merged